# Generated by Django 6.1 on 2026-08-21 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('status', models.CharField(choices=[('pending', 'Oczekujący'), ('processing', 'W trakcie'), ('completed', 'Zakończony'), ('failed', 'Błąd')], default='pending', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='AuditMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=100)),
                ('value', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('warning', 'Ostrzeżenie'), ('error', 'Błąd')], default='ok', max_length=20)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='auditor.audit')),
            ],
            options={
                'ordering': ['category', 'key'],
            },
        ),
    ]
