# Generated by Django 6.1 on 2026-08-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditmetric',
            name='current_value',
            field=models.TextField(blank=True, default='', help_text='Zastany fragment/wartość ze strony powiązana z tą metryką (np. treść <title>, lista URL-i obrazków bez ALT).'),
        ),
    ]
