# Generated by Django 6.1 on 2026-08-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0002_auditmetric_current_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='senuto_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='audit',
            name='senuto_top10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='audit',
            name='senuto_top3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='audit',
            name='senuto_top50',
            field=models.IntegerField(default=0),
        ),
    ]
