# Generated by Django 6.1 on 2026-08-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0003_audit_senuto_history_audit_senuto_top10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='senuto_history',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
