# Generated by Django 6.1 on 2026-09-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0004_alter_audit_senuto_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='ga4_history',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='audit',
            name='ga4_organic_sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='audit',
            name='ga4_property_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='ga4_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
