# Generated by Django 6.1 on 2026-09-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0005_audit_ga4_history_audit_ga4_organic_sessions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='ga4_channels_history',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='audit',
            name='ga4_insights',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='audit',
            name='ga4_selected_lead_event',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
