# Generated by Django 6.1 on 2026-09-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0006_audit_ga4_channels_history_audit_ga4_insights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='gsc_top_gainers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='audit',
            name='gsc_top_losers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='audit',
            name='gsc_total_clicks_current',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='audit',
            name='gsc_total_clicks_previous',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='audit',
            name='gsc_yoy_change_percent',
            field=models.FloatField(default=0.0),
        ),
    ]
