# Generated by Django 6.1 on 2026-09-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0007_audit_gsc_top_gainers_audit_gsc_top_losers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='gsc_page_commentary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='audit',
            name='gsc_query_commentary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='audit',
            name='gsc_top_page_gainers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='audit',
            name='gsc_top_page_losers',
            field=models.JSONField(default=list),
        ),
    ]
