# Generated by Django 6.1 on 2026-09-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0008_audit_gsc_page_commentary_audit_gsc_query_commentary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditmetric',
            name='status',
            field=models.CharField(choices=[('ok', 'OK'), ('warning', 'Ostrzeżenie'), ('error', 'Błąd'), ('info', 'Informacyjne (Opcjonalne)')], default='ok', max_length=20),
        ),
    ]
