# Generated by Django 6.1 on 2026-09-10 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0010_audit_owner_encrypted_token_and_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('page_type', models.CharField(choices=[('homepage', 'Strona główna'), ('category', 'Strona kategorii'), ('product', 'Strona produktu'), ('blog', 'Wpis na blogu'), ('offer', 'Strona ofertowa'), ('other', 'Inna podstrona')], default='other', max_length=20)),
                ('metrics_data', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Oczekujący'), ('processing', 'W trakcie'), ('completed', 'Zakończony'), ('failed', 'Błąd')], default='pending', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='auditor.audit')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('audit', 'url'), name='unique_page_url_per_audit')],
            },
        ),
    ]
