# Generated by Django 6.1 on 2026-09-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0011_auditedpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditmetric',
            name='status',
            field=models.CharField(choices=[('ok', 'OK'), ('warning', 'Ostrzeżenie'), ('error', 'Błąd'), ('info', 'Informacyjne (Opcjonalne)'), ('skipped', 'Nie do zbadania')], default='ok', max_length=20),
        ),
    ]
