# Generated by Django 6.1 on 2026-09-23 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0012_alter_auditmetric_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('citation_rate', models.IntegerField(default=0)),
                ('stability', models.CharField(choices=[('stable', 'STABLE'), ('volatile', 'VOLATILE'), ('absent', 'ABSENT')], default='absent', max_length=20)),
                ('cited_positions', models.JSONField(blank=True, default=list)),
                ('competitors', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Pytanie GEO',
                'verbose_name_plural': 'Pytania GEO',
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='GeoRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('answer', models.TextField(blank=True, default='')),
                ('citations', models.JSONField(blank=True, default=list)),
                ('brand_cited', models.BooleanField(default=False)),
                ('brand_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='auditor.geoquery')),
            ],
            options={
                'verbose_name': 'Powtórzenie GEO',
                'verbose_name_plural': 'Powtórzenia GEO',
                'ordering': ['attempt', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='GeoStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=253)),
                ('status', models.CharField(choices=[('pending', 'Oczekujące'), ('processing', 'W trakcie'), ('completed', 'Zakończone'), ('failed', 'Błąd')], default='pending', max_length=20)),
                ('overall_score', models.IntegerField(default=0)),
                ('repetitions', models.PositiveSmallIntegerField(default=5)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geo_studies', to='auditor.audit')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geo_studies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Badanie GEO',
                'verbose_name_plural': 'Badania GEO',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='geoquery',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='auditor.geostudy'),
        ),
    ]
