# Generated by Django 6.1 on 2026-09-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0013_geoquery_georun_geostudy_geoquery_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='georun',
            name='brand_mentioned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='georun',
            name='visibility',
            field=models.CharField(choices=[('linked_citation', 'Cytowanie z linkiem'), ('brand_mention', 'Wzmianka o marce'), ('absent', 'Brak')], default='absent', max_length=20),
        ),
        migrations.AddField(
            model_name='geostudy',
            name='brand_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
