# Generated by Django 6.1 on 2026-09-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0014_georun_brand_mentioned_georun_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geostudy',
            name='competitors_input',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
