# Generated by Django 6.1 on 2026-09-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0016_recalculate_geo_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoquery',
            name='stability',
            field=models.CharField(choices=[('stable', 'Stabilna'), ('volatile', 'Nierównomierna'), ('absent', 'Brak cytowania')], default='absent', max_length=20),
        ),
        migrations.AlterField(
            model_name='georun',
            name='visibility',
            field=models.CharField(choices=[('linked_citation', 'Cytowanie z linkiem'), ('brand_mention', 'Wzmianka o marce'), ('absent', 'Brak cytowania')], default='absent', max_length=20),
        ),
    ]
