# Generated by Django 6.1 on 2026-09-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0017_alter_geoquery_stability_alter_georun_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='ga4_account_email',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='audit',
            name='gsc_site_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
