# Generated by Django 6.1 on 2026-10-04 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0018_audit_ga4_account_email_audit_gsc_site_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default='', max_length=254)),
                ('refresh_token_encrypted', models.TextField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Konto Google',
                'verbose_name_plural': 'Konta Google',
            },
        ),
    ]
