# Generated by Django 6.1 on 2026-10-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0020_move_tokens_to_google_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='analytics_only',
            field=models.BooleanField(default=False),
        ),
    ]
