"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$i-m83bz70%li(cludhrs9p4dh005s2aux7u4q@5ipmjk=u8bt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'auditor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# RAG engine (auditor.services.rag.RAGEngine)

OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')

# Model embeddingów OpenAI - "text-embedding-ada-002" jako domyślny, ponieważ jest
# dostępny na wszystkich kontach/projektach OpenAI (w przeciwieństwie do nowszych
# modeli "text-embedding-3-*", które wymagają osobnego przyznania dostępu i bez niego
# zwracają błąd 403 model_not_found). Nazwę można nadpisać przez zmienną środowiskową.
OPENAI_EMBEDDING_MODEL = os.environ.get('OPENAI_EMBEDDING_MODEL', 'text-embedding-ada-002')

# Google PageSpeed Insights (auditor.services.pagespeed.PageSpeedService)

PAGESPEED_API_KEY = os.environ.get('PAGESPEED_API_KEY', '')

# Senuto API - statystyki widoczności domeny (auditor.services.senuto.SenutoService)

SENUTO_API_KEY = os.environ.get('SENUTO_API_KEY', '')

# Google Analytics 4 - integracja OAuth 2.0 "Zaloguj się przez Google"
# (auditor.services.ga4_service.GA4OAuthService, auditor.views.start_ga4_auth/ga4_callback).
GA4_CLIENT_SECRETS_FILE = BASE_DIR / 'client_secret.json'
# Zakres GA4 (Analytics Data API) + GSC (Search Console API, auditor.services.gsc_service.GSCService) -
# oba proszone w jednym ekranie zgody Google, żeby nie wymagać osobnego logowania dla GSC.
GA4_SCOPES = [
    'https://www.googleapis.com/auth/analytics.readonly',
    'https://www.googleapis.com/auth/webmasters.readonly',
]
GA4_REDIRECT_URI = os.environ.get('GA4_REDIRECT_URI', 'http://127.0.0.1:8000/ga4/callback/')

if DEBUG:
    # google-auth-oauthlib domyślnie wymaga HTTPS w authorization_response. Lokalny
    # serwer deweloperski Django (http://127.0.0.1:8000) tego nie spełnia, dlatego
    # WYŁĄCZNIE w trybie DEBUG (nigdy na produkcji) wyłączamy tę weryfikację.
    os.environ.setdefault('OAUTHLIB_INSECURE_TRANSPORT', '1')


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
